### ISSUE TITLE
gyp error

### ISSUE THREAD

**Issue by jordanmmck** [SetProtocol/setprotocol.js#370]
I'm not able to install setprotocol.js due to a gyp error. I have Xcode Command Line Tools installed and working fine.

Command run: `yarn add setprotocol.js`

OS: macOS Catalina 10.15.4 (19E287)

`node -v`: v13.13.0
`yarn -v`: 1.22.4

```
2 warnings and 10 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jordan/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/jordan/.nvm/versions/node/v13.13.0/bin/node" "/Users/jordan/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jordan/Development/set-tester/node_modules/scrypt
```

Apologies if the error is on my end. But the only solutions I can find is to installing/re-installing `xcode-select` which I've already done.

**Comment by cavanmflynn** [comment]
I'm getting the same when attempting to install this package, `set-protocol-contracts`, or `set-protocol-viewers`. This looks to be caused by the ancient version of web3 being used (`v1.0.0-beta.36`).

Possible to prioritize a `web3` update?

**Comment by tiagosiebler** [comment]
Have you tried using any pre-10 node version? The readme does state:
> Do not use Node version 10+ as it may have issues during npm install or yarn install with the sha3 package. Use nvm install 9.11.1 && nvm use 9.11.1 for now.

**Comment by hamidziadzadeh** [comment]
@jordanmmck use `--ignore-engines` flag when you try to install `setprotocol.js`
I had the same issue and successfully installed `v1.2.9` on node `v10.22.1` with that flag.
